apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    app: {{ include "..name" . }}
    chart: {{ include "..chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    cluster: {{ .Values.cluster }}
    name: {{ include "..name" . }}
    role: {{ .Values.role }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "..name" . }}
      release: {{ .Release.Name }}
      cluster: {{ .Values.cluster }}
      name: {{ include "..name" . }}
      role: {{ .Values.role }}
  strategy:
    type: RollingUpdate
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: {{ include "..name" . }}
        release: {{ .Release.Name }}
        cluster: {{ .Values.cluster }}
        name: {{ include "..name" . }}
        role: {{ .Values.role }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "..name" . }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
          {{- range $k, $v := .Values.environmentVariables }}
            - name: {{ quote $k }}
              value: {{ quote $v }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: {{ include "..name" . }}-secret
              readOnly: true
              mountPath: /usr/src/app/secret
            - name: {{ include "..name" . }}-config
              readOnly: true
              mountPath: /usr/src/app/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 5
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml . | indent 8 }}
      {{- end }}
      volumes:
      - name: {{ include "..name" . }}-secret
        secret:
          secretName: {{ include "..name" . }}-secret
      - name: {{ include "..name" . }}-config
        configMap:
          name: {{ include "..name" . }}-config